//go:build cgo

// Code generated by rcflags; DO NOT EDIT.

package gopher

// #cgo CFLAGS: -I/usr/include/R/
// #cgo LDFLAGS: -L/usr/lib64/R/lib -lR -lpcre2-8 -llzma -lbz2 -lz -ltirpc -lrt -ldl -lm -licuuc -licui18n
// #define R_NO_REMAP
// #include <R.h>
// #include <Rinternals.h>
import "C"
